# Readynas-to-Telegraf Configuration File
#
# Copyright (c) 2020 Ross A. Stewart
#
# You should have received a copy of the MIT license with
# this file. If not, please or visit : https://github.com/rosskouk/readynas-to-influxdb/blob/master/LICENSE
#
#
# This file should be renamed to config.yaml

# SNMP details
snmp:
    version: 2

# Netgear ReadyNAS details
readynas:
    host: nas.example.com
    community: snmp_community_string
